"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import calldetail as components_calldetail
from typing import Optional


@dataclasses.dataclass
class GetCallRequest:
    call_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'call_id', 'style': 'simple', 'explode': False }})
    r"""The call id to retrieve call history for."""
    



@dataclasses.dataclass
class GetCallResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    call_detail: Optional[components_calldetail.CallDetail] = dataclasses.field(default=None)
    r"""Successfully retrieved an agent."""
    

