"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import phonenumber as components_phonenumber
from typing import Optional


@dataclasses.dataclass
class GetPhoneNumberRequest:
    phone_number: str = dataclasses.field(metadata={'path_param': { 'field_name': 'phone_number', 'style': 'simple', 'explode': False }})
    r"""Phone number in E.164 format to retreive more information."""
    



@dataclasses.dataclass
class GetPhoneNumberResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    phone_number: Optional[components_phonenumber.PhoneNumber] = dataclasses.field(default=None)
    r"""Successfully retrieved a phone number."""
    

