"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from retellclient import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PhoneNumber:
    r"""Phone number associated with the call."""
    agent_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('agent_id') }})
    r"""Unique agent id to associate with this phone number. Can be updated with [Update Phone Agent](/api/update-phone-agent)."""
    area_code: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('area_code') }})
    r"""The area code of the number. This is a 3 digit integer."""
    last_modification_timestamp: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('last_modification_timestamp') }})
    r"""Last modification timestamp (milliseconds since epoch). Either the time of last update or creation if no updates available."""
    phone_number: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phone_number') }})
    r"""Unique phone number you purchased in E.164 format. This number is set up to handle inbound phone calls, and can be used for outbound phone calls with [Create Phone Call](/api/create-phone-call)."""
    phone_number_pretty: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('phone_number_pretty') }})
    r"""Unique phone number you purchased in pretty human readable format. Example: (415) 909-5857."""
    

