configured_endpoints: 61
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/retell%2Ftoddlzt-3f48eaf4290f7dadceeef9adfbb9da21fd66d7f0fab8302c870ebc71cf1606ee.yml
openapi_spec_hash: fee28663bf0780966032c472db6ba3fc
config_hash: 16d10f2313d6daf2f4a74fdaf84d25e1
