# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, TypeAlias

from .._models import BaseModel

__all__ = [
    "ChatCreateChatCompletionResponse",
    "Message",
    "MessageMessageBase",
    "MessageToolCallInvocationMessageBase",
    "MessageToolCallResultMessageBase",
    "MessageNodeTransitionMessageBase",
    "MessageStateTransitionMessageBase",
]


class MessageMessageBase(BaseModel):
    content: str
    """Content of the message"""

    role: Literal["agent", "user"]
    """Documents whether this message is sent by agent or user."""

    created_timestamp: Optional[int] = None
    """Create timestamp of the message"""

    message_id: Optional[str] = None
    """Unique id of the message"""


class MessageToolCallInvocationMessageBase(BaseModel):
    arguments: str
    """Arguments for this tool call, it's a stringified JSON object."""

    name: str
    """Name of the function in this tool call."""

    role: Literal["tool_call_invocation"]
    """This is a tool call invocation."""

    tool_call_id: str
    """Tool call id, globally unique."""

    created_timestamp: Optional[int] = None
    """Create timestamp of the message"""

    message_id: Optional[str] = None
    """Unique id of the message"""

    thought_signature: Optional[str] = None
    """Optional thought signature from Google Gemini thinking models.

    This is used internally to maintain reasoning chain in multi-turn function
    calling.
    """


class MessageToolCallResultMessageBase(BaseModel):
    content: str
    """Result of the tool call, can be a string, a stringified json, etc."""

    role: Literal["tool_call_result"]
    """This is the result of a tool call."""

    tool_call_id: str
    """Tool call id, globally unique."""

    created_timestamp: Optional[int] = None
    """Create timestamp of the message"""

    message_id: Optional[str] = None
    """Unique id of the message"""

    successful: Optional[bool] = None
    """Whether the tool call was successful."""


class MessageNodeTransitionMessageBase(BaseModel):
    role: Literal["node_transition"]
    """This is a node transition."""

    created_timestamp: Optional[int] = None
    """Create timestamp of the message"""

    former_node_id: Optional[str] = None
    """Former node id"""

    former_node_name: Optional[str] = None
    """Former node name"""

    message_id: Optional[str] = None
    """Unique id of the message"""

    new_node_id: Optional[str] = None
    """New node id"""

    new_node_name: Optional[str] = None
    """New node name"""

    transition_type: Optional[Literal["global", "global_go_back", "interrupt_go_back", "normal"]] = None
    """How this node was reached.

    "global" means a global node transition, "global_go_back" means returning from a
    global node, "interrupt_go_back" means going back due to user interruption, and
    "normal" means a regular edge transition.
    """


class MessageStateTransitionMessageBase(BaseModel):
    role: Literal["state_transition"]
    """This is a state transition."""

    created_timestamp: Optional[int] = None
    """Create timestamp of the message"""

    former_state_name: Optional[str] = None
    """Former state name"""

    message_id: Optional[str] = None
    """Unique id of the message"""

    new_state_name: Optional[str] = None
    """New state name"""


Message: TypeAlias = Union[
    MessageMessageBase,
    MessageToolCallInvocationMessageBase,
    MessageToolCallResultMessageBase,
    MessageNodeTransitionMessageBase,
    MessageStateTransitionMessageBase,
]


class ChatCreateChatCompletionResponse(BaseModel):
    messages: List[Message]
    """
    New messages generated by the agent during this completion, including any tool
    call invocations and their results. Does not include the original input
    messages.
    """
